install:
	#due to conflict in pip and older versions of the packages they are done manually not with the -r
	pip install deep_phonemizer~=0.0.19
	pip install	Flask~=3.0.0
	pip install inflect~=6.0.4
	pip install nltk~=3.8.1
	pip install numpy~=1.23.5
	pip install pandas~=2.0.0
	pip install pydub~=0.25.1
	pip installscipy~=1.10.1
	pip install torch~=2.0.0
	pip install tqdm~=4.65.0
	pip install Unidecode~=1.3.6
	pip install transformers~=4.30.2

live:
	source Gladosv2/bin/activate && uvicorn Glados_engine:app --reload --host 0.0.0.0 --port 8000

run:
	 python Glados.py
